[2022-11-16 15:35:30,578] {taskinstance.py:1160} INFO - Dependencies all met for <TaskInstance: MSSQL_connection.load manual__2022-11-16T15:35:19.410655+00:00 [queued]>
[2022-11-16 15:35:30,593] {taskinstance.py:1160} INFO - Dependencies all met for <TaskInstance: MSSQL_connection.load manual__2022-11-16T15:35:19.410655+00:00 [queued]>
[2022-11-16 15:35:30,593] {taskinstance.py:1357} INFO - 
--------------------------------------------------------------------------------
[2022-11-16 15:35:30,594] {taskinstance.py:1358} INFO - Starting attempt 1 of 1
[2022-11-16 15:35:30,594] {taskinstance.py:1359} INFO - 
--------------------------------------------------------------------------------
[2022-11-16 15:35:30,624] {taskinstance.py:1378} INFO - Executing <Task(PythonOperator): load> on 2022-11-16 15:35:19.410655+00:00
[2022-11-16 15:35:30,637] {standard_task_runner.py:52} INFO - Started process 1708 to run task
[2022-11-16 15:35:30,646] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'MSSQL_connection', 'load', 'manual__2022-11-16T15:35:19.410655+00:00', '--job-id', '28', '--raw', '--subdir', 'DAGS_FOLDER/pythonAirflowMSSQL.py', '--cfg-path', '/tmp/tmprtproxzi', '--error-file', '/tmp/tmpmk5pwiij']
[2022-11-16 15:35:30,648] {standard_task_runner.py:80} INFO - Job 28: Subtask load
[2022-11-16 15:35:30,753] {task_command.py:370} INFO - Running <TaskInstance: MSSQL_connection.load manual__2022-11-16T15:35:19.410655+00:00 [running]> on host 5036e10e6c0b
[2022-11-16 15:35:30,923] {taskinstance.py:1572} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=MSSQL_connection
AIRFLOW_CTX_TASK_ID=load
AIRFLOW_CTX_EXECUTION_DATE=2022-11-16T15:35:19.410655+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-11-16T15:35:19.410655+00:00
[2022-11-16 15:35:30,990] {base.py:68} INFO - Using connection ID '***_mssql' for task execution.
[2022-11-16 15:35:31,269] {sql.py:415} INFO - Done loading. Loaded a total of 2 rows
[2022-11-16 15:35:31,271] {python.py:173} INFO - Done. Returned value was: Data loading compete.
[2022-11-16 15:35:31,320] {taskinstance.py:1401} INFO - Marking task as SUCCESS. dag_id=MSSQL_connection, task_id=load, execution_date=20221116T153519, start_date=20221116T153530, end_date=20221116T153531
[2022-11-16 15:35:31,384] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-11-16 15:35:31,463] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
